# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'buttons.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


        layout = QVBoxLayout()
        layout.addWidget(self.label)  
        layout.addWidget(self.b1)
        self.setLayout(layout)

    def openfolder(self):
        while true: 
            path = os.getcwd()
            file = QFileDialog.getOpenFileName(self, "Open an image", path)#this line opens the directory of the current path. 
            self.label.setPixmap(QPixmap(file)) #this line just opens the photo
            print(file[0]) 
            #instead of print(file) i want a list array that 
            #is stored on a separate .py file, which updates every time i append
            #to it from this main file. 
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.b1.setStatusTip(_translate("MainWindow", "Add a photo"))
        self.b1.setText(_translate("MainWindow", "Add"))
