# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dropdown.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AlbumLabel = QtWidgets.QLabel(self.centralwidget)
        self.AlbumLabel.setGeometry(QtCore.QRect(20, 50, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.AlbumLabel.setFont(font)
        self.AlbumLabel.setTextFormat(QtCore.Qt.AutoText)
        self.AlbumLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.AlbumLabel.setObjectName("AlbumLabel")
        self.comboAlbum = QtWidgets.QComboBox(self.centralwidget)
        self.comboAlbum.setEnabled(True)
        self.comboAlbum.setGeometry(QtCore.QRect(10, 130, 161, 41))
        self.comboAlbum.setEditable(False)
        self.comboAlbum.setCurrentText("")
        self.comboAlbum.setObjectName("comboAlbum")
        self.addAlbum = QtWidgets.QPushButton(self.centralwidget)
        self.addAlbum.setGeometry(QtCore.QRect(180, 130, 21, 23))
        self.addAlbum.setObjectName("addAlbum")

        self.addAlbum.clicked.connect(self.add)

        self.allPhotos = QtWidgets.QPushButton(self.centralwidget)
        self.allPhotos.setGeometry(QtCore.QRect(390, 80, 111, 31))
        self.allPhotos.setObjectName("allPhotos")
        self.FacesLabel = QtWidgets.QLabel(self.centralwidget)
        self.FacesLabel.setGeometry(QtCore.QRect(50, 340, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.FacesLabel.setFont(font)
        self.FacesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.FacesLabel.setObjectName("FacesLabel")
        self.comboFaces = QtWidgets.QComboBox(self.centralwidget)
        self.comboFaces.setEnabled(True)
        self.comboFaces.setGeometry(QtCore.QRect(10, 390, 161, 41))
        self.comboFaces.setEditable(False)
        self.comboFaces.setCurrentText("")
        self.comboFaces.setObjectName("comboFaces")
        self.albumName = QtWidgets.QLineEdit(self.centralwidget)
        self.albumName.setGeometry(QtCore.QRect(10, 100, 161, 20))
        self.albumName.setObjectName("albumName")
        self.removeAlbum = QtWidgets.QPushButton(self.centralwidget)
        self.removeAlbum.setGeometry(QtCore.QRect(180, 150, 21, 23))
        self.removeAlbum.setObjectName("removeAlbum")

        self.removeAlbum.clicked.connect(self.remove)

        self.renameAlbum = QtWidgets.QPushButton(self.centralwidget)
        self.renameAlbum.setGeometry(QtCore.QRect(180, 100, 21, 23))
        self.renameAlbum.setObjectName("renameAlbum")

        self.renameAlbum.clicked.connect(self.rename)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AlbumLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Albums</span></p></body></html>"))
        self.addAlbum.setText(_translate("MainWindow", "+"))
        self.allPhotos.setText(_translate("MainWindow", "All Photos"))
        self.FacesLabel.setText(_translate("MainWindow", "Faces"))
        self.removeAlbum.setText(_translate("MainWindow", "-"))
        self.renameAlbum.setText(_translate("MainWindow", "R"))

    def add(self):
        self.comboAlbum.addItem("unnamed")

    def remove(self):
        self.comboAlbum.removeItem(self.comboAlbum.currentIndex())

    def rename(self):
        text = self.albumName.text()
        if(text == ""):
            self.comboAlbum.setItemText(self.comboAlbum.currentIndex(),"unnamed")
        else:
            self.comboAlbum.setItemText(self.comboAlbum.currentIndex(),text)
        self.albumName.clear()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
